# To create a blank environment with only Python 3.x installed, run `mamba create -n your_env_name python=3.x`.
# To create an environment from an `environment-dev.yaml` file, run `mamba env create -f environment-dev.yaml`.
# To activate an environment, run `mamba activate your_env_name` (or `conda activate your_env_name` on Windows).
# To deactivate an environment, run `mamba deactivate` (or `conda deactivate` on Windows).
# To install a package in an environment without an `environment-dev.yaml` file, run `mamba install -n your_env_name package-name`.
# To install a package in an environment with an `environment-dev.yaml` file, first add the package you want to install to the file and then run `mamba env update -f environment-dev.yaml --prune`.
# To remove a package from an environment, run `mamba remove -n your_env_name package-name`.
# To remove an environment, run `mamba remove -n your_env_name --all`.
# To list all environments, run `mamba env list`.
# To list all packages in the current environment, run `mamba list`.

# ! After creating the environment, you must install the following package(s) manually. This can not be done through the environment file (see https://github.com/conda/conda/issues/6805).
# ! pip install git+https://github.com/facebookresearch/pytorch3d.git@stable

name: python_utils

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # Base Python
  - python=3.10
  - pip

  # Development tools
  - pre-commit
  - ipython
  - ipykernel
  - pytest

  # Logging
  - tqdm
  - loguru

  # Pydantic
  - pydantic

  # PyTorch
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - lightning

  # PyTorch3D
  - fvcore
  - iopath

  # Scientific
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - rtree

  # Database manipulation
  - pandas

  # Geospatial data
  - geopandas
  - shapely
